version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - ${DB_EXTERNAL_PORT}:3306
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
      - geophoto-db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"

  server:
    image: cosmtrek/air
    working_dir: /server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - IMAGE_PATH=${IMAGE_PATH}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./server:/server
    links:
      - "db:db"

volumes:
  geophoto-db: