version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - "${PORT}:3306"
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: "${ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
